services:
  constructo:
    container_name: constructo-app
    image: devitools/hyperf:8.3-arm-dev
    working_dir: /opt/www
    volumes:
      - ./:/opt/www
    environment:
      - SONAR_TOKEN=${SONAR_TOKEN:-undefined}
    entrypoint: [ 'tail', '-f', '/dev/null' ]
    restart: on-failure
